---
output: 
  pdf_document:
    citation_package: natbib
    latex_engine: pdflatex
    template: tex-ms.tex
title: "Credit risk distribution and capital savings"
subtitle: ""
thanks: ""
date: # Today, unless specified. In smaller font if specified to allow for version numbering
author:
- name: Lucas Avezum
  affiliation: Tilburg University; l.avezum@uvt.nl; +31134664531;  Warandelaan 2, 5037 AB Tilburg, NL, The Netherlands 

abstract: 
keywords: 
JEL classification: 
toc: false
geometry: margin= 1in
#fontfamily: mathpazo
fontsize: 12pt
#spacing: onehalf
bibliography: ../../../Auxiliar/mybibfile.bib
biblio-style: apsr
citecolor: black
urlcolor:
linkcolor: blue
anonymous: false # quickly sanitizes manuscript for blind review if 'true'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = F, 
                      error = F, 
                      tidy = T, 
                      tidy.opts=list(width.cutoff=50), 
                      collapse = T,
                      warning=FALSE,
                      error=FALSE,
                      message = FALSE, 
                      comment = "",
                      fig.cap = " ",
                      cache = TRUE)
# These options are tuned for manuscript/presentation. 
# They basically run R in the background except for spitting out figures/tables
# They also cache results so that you don't have to run your whole analysis every time you fix a typo
```


Extended abstract {-}
=================


This paper shows that higher-order moments of the distribution of banks' portfolio credit risk, in addition to its average, are important factors of risk-weights (RWs) variability across banks. More specifically, two distributions of probabilities of default (PD) with the same average but different variance result in different capital charges. Using a novel hand-collected dataset, I propose a measure that disantangles this PD distribution effect from the portfolio's average contribution to capital requirements. I estimate the impact of this measure on banks' performance. 

Under the Internal ratings-based approach (IRB) banks supply their own risk estimates to regulatory formulas which determine the amount of capital banks have to hold for each asset. Importantly, these formulas are concave. This means, by Jensen’s inequality, that the sum of capital charges for two assets is lower than the charge for their average (in terms of PD). More generally, the distribution of credit risk matters to calculate capital requirements with, for instance, disperse portfolios yielding relatively lower capital charges. 

To calculate the PD distribution contribution on capital requirements net from the average effect, one needs data on individual or grouped assets' regulatory risk parameters. However, data at such granularity is not available in the common balance sheet datasets. Although very detailed, datasets from credit registers are restricted to one country, and may still lack the relevant information. Therefore, to overcome data limitations I collected information on the distribution of credit risk parameters (PD, EAD and LGD) from banks' individual Pillar-3 reports. The sample consists of 50 large banking groups, from 10 countries, that have adopted the IRB approach. For each bank, I collected consolidated information from the year the IRB approach was approved until 2018. The dataset distinguishes between wholesale, retail and equity portfolios and, in most cases, between their sub-categories (for instance, corporate and sovereign for wholesale and real estate and qualifying revolving for retail). This level of portfolio breakdown is important because regulatory formulas vary across categories, in addition to allowing me to control for variation in capital requirements due to portfolio mix (sovereign portfolios require less capital than corporate). I augment my dataset with balance sheet information obtained from Orbis’ historical disks from 2001 to 2018 and include another 81 banks which calculate capital requirements only under the standardized approach (SA banks) until 2018, which act as a control group in our empirical analysis.

With this unique dataset, I start by analyzing the relative importance of the PD distribution effect to banks' overall RW, both in cross-section and time. Following the method proposed by @cannata2012inside I find that the PD distribution effect accounts for 25% of RW variation. Moreover, capital savings from the PD distribution effect are inversely correlated with the average PD contribution, which suggest that banks holding, high average PD portfolios reduce capital requirements by having, for instance, more disperse PD distributions. Conversely, the time decomposition analysis shows that banks, since introduction of the IRB approach, have decreased the amount of capital savings due to the PD distribution effect. 

I then extend the analysis to find out whether banks adjust their portfolio risk distribution in response to capital requirement shocks. In the spirit of @gropp2018banks, I explore the 2011 EBA capital exercise as a quasi-natural experiment. This was a strong and unexpected test to the solvency of 63 European banks that resulted in a recommendation for these banks to build up their capital buffer to reach a 9.0% core tier 1 capital ratio by June 2012. Identification of the effect of higher capital requirements on banks’ portfolio risk distribution comes from correlating changes in the _capital savings_ measure around the exercise to the distance to achieve the 9.0% required ratio for banks that participated in the exercise. Once established that banks adjust their portfolio risk distribution to achieve regulatory capital requirements, a natural extension is to quantify the effect of these changes on capital ratio and evaluate if these changes impact other variables of interest, such as, return on equity, and risk-taking. To solve endogeneity concerns – for instance, worse capitalized banks have stronger incentives to adjust their portfolios – I use the Basel 2 adoption year across countries as an instrument for the PD distribution effect.

Taken together, the results show that strategic portfolio choice, in terms of credit risk, is an important way banks can reduce capital charges while maintaining their average portfolio risk and return on equity. 


\newpage
\singlespacing

### JEL classification codes {-}
G21, G28, G11

### Keywords {-}
Internal ratings-based models, Risk-weighted assets dispersion, Regulatory arbitrage



# References
