---
title: "Formula_sensitivity"
author: "Lucas Avezum"
date: "April 29, 2019"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

rm(list = ls())
getwd()
knitr::opts_chunk$set(fig.width=6, fig.height=4)  

## Load the libraries we will be using
library(tidyverse)
library(scales)
library(plyr)
library(gridExtra)
library(DescTools)
library(lfe)
library(stargazer)
```





```{r parameters and data, echo=FALSE, include=FALSE}
set.seed(123)
LGD <- 0.2
M   <- 2.5
grid  <- seq(0.0001, 1, by=0.00001) 
grid_2  <- seq(0, 10, by=0.01) 
PD_1 <- rlnorm(length(grid),-4,0.1)
PD_1[PD_1<0] <- 0.0001
PD_1_avg <- mean(PD_1)
PD_1_sd <- sd(PD_1)
PD_2 <- rlnorm(length(grid),-4,0.5)
PD_2[PD_2<0] <- 0.0001
PD_2[PD_2>0.9999] <- 0.9999
PD_2_avg <- mean(PD_2)
PD_2_sd <- sd(PD_2)
```


```{r formulas, echo=FALSE, include=FALSE}
mapping_wholesale <- function(PD,LGD,M,alpha,portfolio){
  R  <- 0.12*(1-exp(-50*PD))/(1-exp(-50))+0.24*(1-(1-exp(-50*PD))/(1-exp(-50)))
  b  <- (0.11852-0.05478*log(PD))^2
  K  <- LGD*(pnorm(((1-R)^(-0.5))*qnorm(PD)+((R/(1-R))^(0.5))*qnorm(alpha))-PD)*((1-1.5*b)^-1*(1+(M-2.5)*b))
  RW <- K*12.5
  data <- data.frame(K,RW,PD,LGD,M,R,portfolio)
  return(data)
}

mapping_retail <- function(PD,LGD,R,alpha,portfolio){
  K  <- LGD*(pnorm(((1-R)^(-0.5))*qnorm(PD)+((R/(1-R))^(0.5))*qnorm(alpha))-PD)
  RW <- K*12.5
  data <- data.frame(K,RW,PD,LGD,M,R,portfolio)
  return(data)
}

mapping_other_retail <- function(PD,LGD,alpha,portfolio){
  R  <- 0.03*(1-exp(-35*PD))/(1-exp(-35))+0.16*(1-(1-exp(-35*PD))/(1-exp(-35)))
  K  <- LGD*(pnorm(((1-R)^(-0.5))*qnorm(PD)+((R/(1-R))^(0.5))*qnorm(alpha))-PD)
  RW <- K*12.5
  data <- data.frame(K,RW,PD,LGD,R,portfolio)
  return(data)
}
```





```{r wholesale vs retail, echo=FALSE}
data <- mapping_wholesale(grid,0.45,2.5,0.999,factor("Corporate"))
data <- rbind(data,mapping_retail(grid,0.45,0.15,0.999,factor("Mortgage")))


p <- ggplot(data = subset(data,subset = PD <0.2),
            mapping = aes(x = PD, y=K, colour = portfolio)) 
p + geom_line(alpha = 1) + 
  labs(x = "PD", 
         y = "Capital requirement per unit of exposure",title = "Figure 1: Wholesale vs Retail") +
  theme_bw()
```
 
```{r LGD sensitivity, echo=FALSE}
data <- mapping_wholesale(grid,0.4,2.5,0.999,factor("LGD = 40%"))
data <- rbind(data,mapping_wholesale(grid,0.45,2.5,0.999,factor("LGD = 45%")))
data <- rbind(data,mapping_wholesale(grid,0.5,2.5,0.999,factor("LGD = 50%")))

p <- ggplot(data = subset(data,subset = PD <0.2),
            mapping = aes(x = PD, y=K, colour = portfolio)) 
p + geom_line(alpha = 1) + 
  labs(x = "PD", 
         y = "Capital requirement per unit of exposure",title = "Figure 2: PD mapping") +
  theme_bw()
```
```{r M sensitivity, echo=FALSE}
data <- mapping_wholesale(grid,0.1,0,0.999,factor("M = 0 year"))
data <- rbind(data,mapping_wholesale(grid,0.1,2.5,0.999,factor("M = 2.5 years")))
data <- rbind(data,mapping_wholesale(grid,0.1,5,0.999,factor("M = 5 years")))

p <- ggplot(data = subset(data,subset = PD <0.2),
            mapping = aes(x = PD, y=K, colour = portfolio)) 
p + geom_line(alpha = 1) + 
  labs(x = "PD", 
         y = "Capital requirement per unit of exposure",title = "Figure 3: PD mapping") +
  theme_bw()
```

```{r LGD_mapping, echo=FALSE}
data <- mapping_wholesale(0.01,grid,2.5,0.999,factor("PD = 1%"))
data <- rbind(data,mapping_wholesale(0.05,grid,2.5,0.999,factor("PD = 5%")))
data <- rbind(data,mapping_wholesale(0.1,grid,2.5,0.999,factor("PD = 10%")))

p <- ggplot(data = subset(data,subset = PD <1),
            mapping = aes(x = LGD, y=K, colour = portfolio)) 
p + geom_line(alpha = 1) + 
  labs(x = "LGD", 
         y = "Capital requirement per unit of exposure",title = "Figure 4: LGD mapping") +
  theme_bw()
```

```{r M_mapping, echo=FALSE}
data <- mapping_wholesale(0.01,0.45,grid_2,0.999,factor("PD = 1%"))
data <- rbind(data,mapping_wholesale(0.05,0.45,grid_2,0.999,factor("PD = 5%")))
data <- rbind(data,mapping_wholesale(0.1,0.45,grid_2,0.999,factor("PD = 10%")))

p <- ggplot(data = data,
            mapping = aes(x = M, y=K, colour = portfolio)) 
p + geom_line(alpha = 1) + 
  labs(x = "Maturity", 
         y = "Capital requirement per unit of exposure",title = "Figure 5: Maturity mapping") +
  theme_bw()
```




```{r savings simulation, echo=FALSE,include=FALSE}

K_bar <- 99991*mapping_wholesale(mean(PD_1),0.45,2.5,0.999,factor("Average PD"))["K"]
K_i <- mapping_wholesale(PD_1,0.45,2.5,0.999,factor("PD distribution"))
new <- summarise(K_i,EAD = Freq(K))
K_total <- K_i  %>%
  group_by(portfolio) %>% 
  summarise_all(sum)

print(K_bar-K_total["K"])
print(K_total["K"]/K_bar-1)

K_bar <- 99991*mapping_wholesale(mean(PD_2),0.45,2.5,0.999,factor("Average PD"))["K"]
K_i <- mapping_wholesale(PD_2,0.45,2.5,0.999,factor("PD distribution"))
K_total <- K_i  %>%
  group_by(portfolio) %>% 
  summarise_all(sum)

print(K_bar-K_total["K"])
print(K_total["K"]/K_bar-1)


K_bar <- 99991*mapping_wholesale(mean(PD_2),0.55,2.5,0.999,factor("Average PD"))["K"]
K_i <- mapping_wholesale(PD_2,0.55,2.5,0.999,factor("PD distribution"))
K_total <- K_i  %>%
  group_by(portfolio) %>% 
  summarise_all(sum)

print(K_bar-K_total["K"])
print(K_total["K"]/K_bar-1)

K_bar <- 99991*mapping_wholesale(mean(PD_2),0.45,0,0.999,factor("Average PD"))["K"]
K_i <- mapping_wholesale(PD_2,0.45,0,0.999,factor("PD distribution"))
K_total <- K_i  %>%
  group_by(portfolio) %>% 
  summarise_all(sum)

print(K_bar-K_total["K"])
print(K_total["K"]/K_bar-1)

```



```{r PD LGD correlation, echo=FALSE}
load("../../Data/Temp/PD_LGD_correlation.Rda")

reg.hdfe1 <- felm(LGD~ PD | Portfolio+Bank|0|0,
                  data = subset(data,subset = PD<1))
robust.hdfe1 <- summary(reg.hdfe1,robust=TRUE)$coefficients[,2]

reg.hdfe2 <- felm(LGD~ PD | Bank|0|0,
                  data = subset(data,subset = PD<1 & Portfolio == "Real estate"))
robust.hdfe2 <- summary(reg.hdfe2,robust=TRUE)$coefficients[,2]

reg.hdfe3 <- felm(LGD~ PD | Bank|0|0,
                  data = subset(data,subset = PD<1 & Portfolio == "Qualifying revolving" ))
robust.hdfe3 <- summary(reg.hdfe3,robust=TRUE)$coefficients[,2]

reg.hdfe4 <- felm(LGD~ PD |  Bank|0|0,
                  data = subset(data,subset = PD<1 & Portfolio == "Other retail"))
robust.hdfe4 <- summary(reg.hdfe4,robust=TRUE)$coefficients[,2]

reg.hdfe5 <- felm(LGD~ PD |  Bank|0|0,
                  data = subset(data,subset = PD<1 & Portfolio == "Corporate"))
robust.hdfe5 <- summary(reg.hdfe5,robust=TRUE)$coefficients[,2]

reg.hdfe6 <- felm(LGD~ PD |  Bank|0|0,
                  data = subset(data,subset = PD<1 & Portfolio == "Banks"))
robust.hdfe6 <- summary(reg.hdfe6,robust=TRUE)$coefficients[,2]

reg.hdfe7 <- felm(LGD~ PD |  Bank|0|0,
                  data = subset(data,subset = PD<1 & Portfolio == "Sovereign"))
robust.hdfe7 <- summary(reg.hdfe7,robust=TRUE)$coefficients[,2]
```
```{r PD LGD table, eval=TRUE, echo=FALSE, results='asis', warning=FALSE, message=FALSE}

stargazer(reg.hdfe1,reg.hdfe2,reg.hdfe3,reg.hdfe4,reg.hdfe5,reg.hdfe6,reg.hdfe7,
          header = FALSE, type="latex", keep.stat = c("n","rsq"), font.size = "small", 
          label = "",
          style = "qje", 
          column.labels   = c("All", "Real estate","Credit cards", "Other retail","Corporates","Banks","Sovereign"),
          dep.var.labels = c("LGD"), column.sep.width = "2pt",
          add.lines = list(c("Portfolio FE", "Yes", "-","-","-","-","-","-"),
                           c("Bank FE","Yes", "Yes","Yes","Yes","Yes","Yes","Yes")))

```          
          
      

