---
title: "JMP report"
author: "Lucas Avezum"
date: "June 6, 2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)                                                             ## excel files and,
library(readxl)                                                            ## load the libraries.
library(data.table)
library(foreign)
library(lubridate)
library(lfe)
library(stargazer)
library(ineq)
library(DescTools)
library(gglorenz)
library(ggplot2)
library(psych)
library(table1)

```
```{r load data, include=FALSE}
load("../../Data/Temp/Raw_data_2.Rda")
lc.wholesale <- data %>% filter(Portfolio_lv1 == "Wholesale") 
lc.wholesale <- Lc(lc.wholesale$PD,lc.wholesale$EAD*lc.wholesale$LGD)

lc.retail <- data %>% filter(Portfolio_lv1 == "Retail") 
lc.retail <- Lc(lc.retail$PD,lc.retail$EAD*lc.retail$LGD)


bankscope <- read_xlsx("../../Data/Temp/BankFocus_Export.xlsx",sheet = 2)
collection <- read_xlsx("../../Data/Temp/First_List_banks.xlsx",sheet = 5)



bankscope <- mutate(bankscope,guo_id=ifelse(is.na(guo_id),id,guo_id))
bankscope <- mutate(bankscope,cap_req1=ifelse(cap_req1=="n.a.",cap_req2,cap_req1))
bankscope <- mutate(bankscope,cap_req2=ifelse(cap_req2=="n.a.",cap_req1,cap_req2))

collection <- mutate(collection,cap_req1=ifelse(cap_req1=="n.a.",cap_req2,cap_req1))
collection <- mutate(collection,cap_req2=ifelse(cap_req2=="n.a.",cap_req1,cap_req2))

bankscope <- filter(bankscope,guo_id==id)
bankscope <- filter(bankscope,cap_req1!="n.a.")
collection <- filter(collection,cap_req1!="n.a.")

bankscope <- mutate(bankscope,total_asset=as.numeric(total_asset),
                    cap_req1 = as.numeric(cap_req1),
                    cap_req2 = as.numeric(cap_req2))
collection <- mutate(collection,total_asset=as.numeric(total_asset),
                    cap_req1 = as.numeric(cap_req1),
                    cap_req2 = as.numeric(cap_req2))

bankscope <- mutate(bankscope,total_asset=total_asset/1000)
collection <- mutate(collection,total_asset=total_asset/1000)

```

```{r data analysis, echo=FALSE,include=FALSE}

bankscope.size <- summarise_if(bankscope,is.numeric,funs(sum),na.rm=TRUE)
collection.size <- summarise_if(collection,is.numeric,funs(sum),na.rm=TRUE)
collection.IRB <- filter(collection,SA==0)
collection.SA <- filter(collection,SA==1)
collection.IRB.collected <- filter(collection,SA==0,collected==1)

```


- Banks in BankScope: 1048

- Banks in target sample: 124

- Relative asset size (target/BankScope): 78.4% 

- IRB banks in target sample: 48

- IRB banks collected: 22

- SA banks in sample: 52

- Unindentified banks in sample: 24




```{r summary stats, echo=FALSE}
table1::label(collection$total_asset) <- "Total assets (bn USD)"
table1::label(collection$cap_req1) <- "Capital ratio (%)"
table1::table1(~ total_asset + cap_req1  | country, data = collection,transpose = TRUE)
```
```{r summary stats 2 , echo=FALSE}
table1::label(collection.IRB.collected$total_asset) <- "Total assets (bn USD)"
table1::label(collection.IRB.collected$cap_req1) <- "Capital ratio (%)"
table1::table1(~ total_asset + cap_req1  | country, data = collection.IRB.collected,transpose = TRUE)
```
```{r summary stats 3 , echo=FALSE}
collection <- mutate(collection, Type=ifelse(SA==0,"SA","IRB"))
table1::label(collection$total_asset) <- "Total assets (bn USD)"
table1::label(collection$cap_req1) <- "Capital ratio (%)"
table1::table1(~ total_asset + cap_req1 | Type, data = collection,transpose = TRUE)
```

```{r sample distribution, echo=FALSE,include=FALSE}
p.total <- ggplot(collection, aes(x="", y=total_asset, fill=country))+
geom_bar(width = 1, stat = "identity") + coord_polar("y", start=0)
p.total

```


```{r lorenz curve, echo=FALSE,include=FALSE}
plot(lc.wholesale,
     col="black",
     type="l",      # !is not working
     lty=1,
     lwd=3,
     main="Lorenz Curve by Portfolio"     
)

lines(lc.retail, lty=2, lwd=3)


legend("topleft",
       c("Wholesale", "Retail"),
       lty=c(1,2,3),
       lwd=3)
```

